force-app/main/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <description>Built for timeline.js</description>
    <label>Timeline</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Timeline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline__c/fields/Background_URL__c.field-meta.xml
<CustomField>
    <fullName>Background_URL__c</fullName>
    <label>Background URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/Timeline_Era__c.object-meta.xml
<CustomObject>
    <label>Timeline Era</label>
    <nameField>
        <displayFormat>TLE-{0000}</displayFormat>
        <label>Timeline Era Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Eras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Era__c/fields/End_Year__c.field-meta.xml
<CustomField>
    <fullName>End_Year__c</fullName>
    <label>End Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <label>Start Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/fields/Timeline__c.field-meta.xml
<CustomField>
    <fullName>Timeline__c</fullName>
    <label>Timeline</label>
    <referenceTo>Timeline__c</referenceTo>
    <relationshipLabel>Timeline Eras</relationshipLabel>
    <relationshipName>Timeline_Eras</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/Timeline_Slide__c.object-meta.xml
<CustomObject>
    <label>Timeline Slide</label>
    <nameField>
        <displayFormat>TLS-{0000}</displayFormat>
        <label>Timeline Slide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Slides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Slide__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <inlineHelpText>Hex value or CSS color name.</inlineHelpText>
    <label>Background Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Background_URL__c.field-meta.xml
<CustomField>
    <fullName>Background_URL__c</fullName>
    <inlineHelpText>URL of an image for the background.</inlineHelpText>
    <label>Background URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Display_Date__c.field-meta.xml
<CustomField>
    <fullName>Display_Date__c</fullName>
    <inlineHelpText>Use this to override the usage of the start/end dates in the slide labeling. Useful if, for example, you want to display only the year and month of an event, but need to specify a specific day for historical accuracy.</inlineHelpText>
    <label>Display Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/End_Year__c.field-meta.xml
<CustomField>
    <fullName>End_Year__c</fullName>
    <label>End Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Allows grouping of events into, well, groups. They will display in the same band of the timeline, with the group's label at the beginning of the band.</inlineHelpText>
    <label>Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Alt_Tag_Text__c.field-meta.xml
<CustomField>
    <fullName>Media_Alt_Tag_Text__c</fullName>
    <description>For accessibility, will be read by screen readers and other assistive technologies.</description>
    <label>Media Alt Tag Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Caption__c.field-meta.xml
<CustomField>
    <fullName>Media_Caption__c</fullName>
    <label>Media Caption</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Credit__c.field-meta.xml
<CustomField>
    <fullName>Media_Credit__c</fullName>
    <label>Media Credit</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Media_Thumbnail__c</fullName>
    <label>Media Thumbnail</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_URL__c.field-meta.xml
<CustomField>
    <fullName>Media_URL__c</fullName>
    <description>Link to a video, google map, etc.</description>
    <label>Media URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <label>Start Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Timeline__c.field-meta.xml
<CustomField>
    <fullName>Timeline__c</fullName>
    <label>Timeline</label>
    <referenceTo>Timeline__c</referenceTo>
    <relationshipLabel>Slides</relationshipLabel>
    <relationshipName>Timeline_Slides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TimelineController.cls
public with sharing class TimelineController {
    
    public string outjson { get; set; }
    
    public TimelineController(){
        outjson = GetTimelineJSON(apexpages.currentPage().getParameters().get('id'));
    }
    
    public string GetTimelineJSON(Id timelineID){
        
        //get the object
        Timeline__c tl = [SELECT Id, Title__c, Subtitle__c, Background_Color__c, Background_URL__c, (
        	SELECT Title__c, Details__c, Start_Year__c, Start_Month__c, Start_Day__c, 
            	End_Year__c, End_Month__c, End_Day__c, Background_URL__c, Background_Color__c,
            	Media_URL__c, Media_Caption__c, Media_Credit__c, Media_Thumbnail__c, Media_Alt_Tag_Text__c,
            	Group__c, Display_Date__c
            from Timeline_Slides__r
        ), (
        	SELECT Title__c, Details__c, Start_Year__c, Start_Month__c, Start_Day__c,
            End_Year__c, End_Month__c, End_Day__c
            from Timeline_Eras__r
        ) FROM Timeline__c WHERE Id = :timelineID];
        
        
        JSONGenerator gen = JSON.createGenerator(true); 
        gen.writeStartObject();
        gen.writeFieldName('title');
        gen.writeStartObject();
        gen.writeFieldName('text');
        gen.writeStartObject();
        gen.writeStringField('headline', tl.Title__c);
        gen.writeStringField('text', tl.Subtitle__c);
        gen.writeEndObject();
        
        //title Background
        if (tl.Background_Color__c != null || tl.Background_URL__c != null){
            gen.writeFieldName('background');
            gen.writeStartObject();
            if (tl.Background_Color__c != null) gen.writeStringField('color', tl.Background_Color__c);
            if (tl.Background_URL__c != null) gen.writeStringField('url', tl.Background_URL__c);
            gen.writeEndObject();
        }
        gen.writeEndObject();        
        
        //eras
        gen.writeFieldName('eras');
        gen.writeStartArray();
        for (Timeline_Era__c e : tl.Timeline_Eras__r){
            gen.writeStartObject();
            
            //text
            gen.writeFieldName('text');
            gen.writeStartObject();
            gen.writeStringField('headline', e.Title__c);
            if (e.Details__c != null) gen.writeStringField('text', e.Details__c);
            gen.writeEndObject();
            
            //dates
            gen.writeFieldName('start_date');
            gen.writeStartObject();
            gen.writeNumberField('year', Integer.valueOf(e.Start_Year__c));
            if (e.Start_Month__c != null) gen.writeNumberField('month', e.Start_Month__c);
            if (e.Start_Day__c != null) gen.writeNumberField('day', e.Start_Day__c);
            gen.writeEndObject();
            
            gen.writeFieldName('end_date');
            gen.writeStartObject();
            gen.writeNumberField('year', Integer.valueOf(e.End_Year__c));
            if (e.End_Month__c != null) gen.writeNumberField('month', e.End_Month__c);
            if (e.End_Day__c != null) gen.writeNumberField('day', e.End_Day__c);
            gen.writeEndObject();
            
            gen.writeEndObject();
        }
        gen.writeEndArray();
        
        gen.writeFieldName('events');
        gen.writeStartArray();
        for (Timeline_Slide__c s : tl.Timeline_Slides__r){
            gen.writeStartObject();
            
            //text
            gen.writeFieldName('text');
            gen.writeStartObject();
            gen.writeStringField('headline', s.Title__c);
            gen.writeStringField('text', s.Details__c);
            gen.writeEndObject();
            
            //start date
            gen.writeFieldName('start_date');
            gen.writeStartObject();
            gen.writeNumberField('year', Integer.valueOf(s.Start_Year__c));
            if (s.Start_Month__c != null) gen.writeNumberField('month', s.Start_Month__c);
            if (s.Start_Day__c != null) gen.writeNumberField('day', s.Start_Day__c);
            gen.writeEndObject();
            
            
            //end date
            if (s.End_Year__c != null){
                gen.writeFieldName('end_date');
                gen.writeStartObject();
                gen.writeNumberField('year', Integer.valueOf(s.End_Year__c));
                if (s.End_Month__c != null) gen.writeNumberField('month', s.End_Month__c);
                if (s.End_Day__c != null) gen.writeNumberField('day', s.End_Day__c);
                gen.writeEndObject();
            }
            
            //display date
            if (s.Display_Date__c != null) gen.writeStringField('display_date', s.Display_Date__c);
            
            //group
            if (s.Group__c != null) gen.writeStringField('group', s.Group__c);
            
            //media
            
            if (s.Media_URL__c != null){
                gen.writeFieldName('media');
                gen.writeStartObject();
                gen.writeStringField('url', s.Media_URL__c);
                if (s.Media_Caption__c != null) gen.writeStringField('caption', s.Media_Caption__c);
                if (s.Media_Credit__c != null) gen.writeStringField('credit', s.Media_Credit__c);
                if (s.Media_Alt_Tag_Text__c != null) gen.writeStringField('alt', s.Media_Alt_Tag_Text__c);
                if (s.Media_Thumbnail__c != null) gen.writeStringField('thumbnail', s.Media_Thumbnail__c);
                gen.writeEndObject();
            }
            
            //background
            if (s.Background_Color__c != null || s.Background_URL__c != null){
                gen.writeFieldName('background');
                gen.writeStartObject();
                if (s.Background_Color__c != null) gen.writeStringField('color', s.Background_Color__c);
                if (s.Background_URL__c != null) gen.writeStringField('url', s.Background_URL__c);
                gen.writeEndObject();
            }

            gen.writeEndObject();
            
        }
        gen.writeEndArray();
        gen.writeEndObject();
        return gen.getAsString();
    }
}