force-app/main/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <description>Built for timeline.js</description>
    <label>Timeline</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Timeline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Era__c/Timeline_Era__c.object-meta.xml
<CustomObject>
    <label>Timeline Era</label>
    <nameField>
        <displayFormat>TLE-{0000}</displayFormat>
        <label>Timeline Era Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Eras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Era__c/fields/End_Year__c.field-meta.xml
<CustomField>
    <fullName>End_Year__c</fullName>
    <label>End Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <label>Start Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/fields/Timeline__c.field-meta.xml
<CustomField>
    <fullName>Timeline__c</fullName>
    <label>Timeline</label>
    <referenceTo>Timeline__c</referenceTo>
    <relationshipLabel>Timeline Eras</relationshipLabel>
    <relationshipName>Timeline_Eras</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timeline_Era__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/Timeline_Slide__c.object-meta.xml
<CustomObject>
    <label>Timeline Slide</label>
    <nameField>
        <displayFormat>TLS-{0000}</displayFormat>
        <label>Timeline Slide Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Slides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Slide__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <inlineHelpText>Hex value or CSS color name.</inlineHelpText>
    <label>Background Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/End_Year__c.field-meta.xml
<CustomField>
    <fullName>End_Year__c</fullName>
    <label>End Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Alt_Tag_Text__c.field-meta.xml
<CustomField>
    <fullName>Media_Alt_Tag_Text__c</fullName>
    <description>For accessibility, will be read by screen readers and other assistive technologies.</description>
    <label>Media Alt Tag Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Caption__c.field-meta.xml
<CustomField>
    <fullName>Media_Caption__c</fullName>
    <label>Media Caption</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Credit__c.field-meta.xml
<CustomField>
    <fullName>Media_Credit__c</fullName>
    <label>Media Credit</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Media_Thumbnail__c</fullName>
    <label>Media Thumbnail</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Media_URL__c.field-meta.xml
<CustomField>
    <fullName>Media_URL__c</fullName>
    <description>Link to a video, google map, etc.</description>
    <label>Media URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Start_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Year__c</fullName>
    <label>Start Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Slide__c/fields/Timeline__c.field-meta.xml
<CustomField>
    <fullName>Timeline__c</fullName>
    <label>Timeline</label>
    <referenceTo>Timeline__c</referenceTo>
    <relationshipLabel>Slides</relationshipLabel>
    <relationshipName>Timeline_Slides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TimelineControllerTest.cls
@IsTest
public with sharing class TimelineControllerTest {
	
    public static Id setup(){
        Timeline__c t = new Timeline__c();
        t.Title__c = 'Test';
        t.Subtitle__c = 'Testing';
        t.Background_Color__c = '#666666';
        insert t;
        
        Timeline_Era__c e = new Timeline_Era__c();
        e.Timeline__c = t.Id;
        e.Start_Year__c = '2001';
        e.End_Year__c = '2010';
        e.Title__c = 'Test Era';
        e.Details__c = 'Test';
        insert e;
        
        Timeline_Slide__c s = new Timeline_Slide__c();
        s.Timeline__c = t.Id;
        s.Title__c = 'Test Slide';
        s.Details__c = 'Test content.';
        s.Background_Color__c = '#003366';
        s.Start_Day__c = 1;
        s.Start_Month__c = 7;
        s.Start_Year__c = '2001';
        s.End_Year__c = '2005';
        s.Media_Alt_Tag_Text__c = '';
        s.Media_Caption__c = '';
        s.Media_Credit__c = '';
        s.Media_Thumbnail__c = '';
        s.Media_URL__c = 'http://www.example.com';
        insert s;
        
        return t.Id;
    }
    
    public static testmethod void testGetJSON(){
        PageReference ref = Page.TimelineDisplay;
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('id', setup());
        TimelineController c = new TimelineController();
        string json = c.GetTimelineJSON(setup());
        System.assert(json.length() > 0);
    }
    
}